### ISSUE TITLE
Improve Getting Started docs

### ISSUE THREAD

**Issue by trevrosen** [hybridgroup/gobot-site#34]
It would be very nice to be able to have some explanation of the major features and architectural components/abstractions right off the bat. I'm creating this issue as a discussion venue for some improvements in that area.

**Comment by trevrosen** [comment]
As next steps in this area, I'd like to propose a dedicated docs page on the Robot abstraction and what it's capable of, as well as an architectural diagram for the main getting started page. I volunteer to put these together.

**Comment by zankich** [comment]
@trevrosen we have a similar page on the Cylon [website](http://cylonjs.com/documentation/architecture/). The architecture is mostly the same, so that is a good starting point as well as some diagrams which  have been put together. Thanks for all the help!

**Comment by deadprogram** [comment]
The site has been considerably updated since this was entered. Please open a new issue for anything specific to the current site. Thanks.
