### ISSUE TITLE
Spark Core imcompatible to Servo

### ISSUE THREAD

**Issue by brasilikum** [hybridgroup/gobot-site#36]
There is an issue open on the gobot repo from december 2014.
While not working, the spark core should not be listed to be compatible with the servo.

**Comment by deadprogram** [comment]
Hi, @Brasilikum 

You are correct, I will look into making that change. Thanks for pointing it out.

**Comment by deadprogram** [comment]
We updated the Particle support to add the tinker-servo sketch in the last release. Now closing. Thanks!
